# Move this file under github (one folder level up)
# same level as BillingUC
# RUN $docker build . -t grpcbillingserver
# RUN $docker images # this should return grpcbillingserver running
# RUN $ docker run -p 8080:8080 grpcbillingserver

# install golang
FROM golang

# install protobuf from source
RUN apt-get update && \
    apt-get -y install git unzip build-essential autoconf libtool

# NOTE: for now, this docker image always builds the current HEAD version of
# gRPC.  After gRPC's beta release, the Dockerfile versions will be updated to
# build a specific version.

# Get the source from GitHub
RUN go get google.golang.org/grpc
# Install protoc-gen-go
RUN go get github.com/golang/protobuf/protoc-gen-go

RUN go env

ADD . /go/src/github

RUN ls /go/src/github/BillingUC

RUN go install github/BillingUC/src/Servers

RUN ls /go/bin/Servers

ENTRYPOINT ["/go/bin/Servers"]

EXPOSE 8080